[package]
name = "eddsa"
edition.workspace = true
version.workspace = true

[dependencies]
num-bigint = {workspace = true}
num-traits = {workspace = true}
lazy_static = {workspace = true}
ark-ec =  { workspace = true }
ark-ff =  { workspace = true }
ark-ed-on-bls12-381 =  { workspace = true }
ark-serialize =  { workspace = true }
rand = {workspace = true}
serde = { workspace = true }
zeroize = {workspace = true}
blake3 = {workspace = true}
eyre = {workspace = true}
hex = {workspace = true}
poseidon2 = {path = "../poseidon2"}
